# Built with Jekyll 3.2.0

# Setup
title:               uSleep Consulting
tagline:             'Bespoke solutions for Telecoms and Service Providers'
#description:         "uSleep Consulting focuses on building simple, maintainable VoIP solutions; Need someone to build or maintain your SIP proxies, Media Services, Provisioning Servers and Monitoring? We've got you covered."
url:                 'https://usleep.consulting'
# baseurl:             '/ed'

# About/contact
author:
  name:              Bucky Wolfe
  url:               https://github.com/igneous
  email:             igneous@usleep.consulting

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme: orange

# Permalinks
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  syntax_highlighter: coderay

# Exclusions from the final site
exclude:
  - optional
  - vendor

# Theme
theme: "ed."
